export const metadata = {
    title: 'Build Pong in React - Interactive Game Development Tutorial | Yatheesh Nagella',
    description: 'Learn game development by building classic Pong! Step-by-step tutorial covering Canvas API, collision detection, AI opponents, and particle effects. Interactive code examples included.',
    keywords: [
      'react game development',
      'pong game tutorial',
      'canvas api tutorial',
      'javascript game programming',
      'collision detection',
      'game physics',
      'particle effects',
      'interactive tutorial',
      'learn game dev',
      'react canvas',
    ],
    authors: [{ name: 'Yatheesh Nagella' }],
    creator: 'Yatheesh Nagella',
    publisher: 'Yatheesh Nagella',
    openGraph: {
      title: 'Build Pong in React - Interactive Tutorial',
      description: 'Master game development fundamentals by building classic Pong with React and Canvas API',
      url: 'https://yatheeshnagella.com/blogs/build-pong-game',
      siteName: 'Yatheesh Nagella Portfolio',
      images: [
        {
          url: '/blog-images/pong-game-og.png',
          width: 1200,
          height: 630,
          alt: 'Build Pong in React Tutorial',
        },
      ],
      locale: 'en_US',
      type: 'article',
    },
    twitter: {
      card: 'summary_large_image',
      title: 'Build Pong in React - Interactive Tutorial',
      description: 'Learn game development by building classic Pong! 🏓',
      images: ['/blog-images/pong-game-og.png'],
      creator: '@YatheeshNagella',
    },
    robots: {
      index: true,
      follow: true,
      googleBot: {
        index: true,
        follow: true,
        'max-video-preview': -1,
        'max-image-preview': 'large',
        'max-snippet': -1,
      },
    },
    category: 'Tutorial',
  };